version: '3'

services:
  backend:
    build:
      context: ./src/backend
      dockerfile: Dockerfile
    ports:
    - ${BACKEND_PORT}:${BACKEND_PORT}
    environment:
      BACKEND_PORT: ${BACKEND_PORT}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_ADDRESS: ${MONGO_ADDRESS}
    networks:
      - postgres_net
      - mognodb_mongodb_net
      - docker_net
    restart: always

  file_server:
    hostname: fileserver
    container_name: fileserver
    build:
      context: ./src/fileServer
      dockerfile: Dockerfile
    volumes:
      - ./files:/go/src/application/files
    ports:
      - ${FILE_BACKEND_PORT}:${FILE_BACKEND_PORT}
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
      FILE_BACKEND_PORT: ${FILE_BACKEND_PORT}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      S3_BUCKET_PATH: ${S3_BUCKET_PATH}
    networks:
      - docker_net
      - postgres_net

  mongodb:
    hostname: mongodb
    image: mongo:4.2.3
    container_name: mongodb
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    volumes:
      - ./data/mongo:/data/db
    # uncomment the below line to setup mongo replica set!  But only after default setup! And then run rs.initiate() in mongo shell
    entrypoint: ["/usr/bin/mongod", "--port", "27072", "--dbpath", "/data/db", "--replSet", "rs0", "--bind_ip", "mongodb,localhost"]
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    networks:
      - mognodb_mongodb_net

  postgres:
    image: postgres:12.3-alpine
    volumes:
      - ./data/pgsql:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST_AUTH_METHOD: password
    networks:
      - postgres_net
        #user: "1001:1001"
    restart: on-failure
    command: -p ${POSTGRES_PORT}

  server:
    build:
      context: ./src/nginx
      dockerfile: Dockerfile
    volumes:
      - /etc/localtime:/etc/localtime/:ro
      - /home/gregory/ssl_nginx/certs:/etc/nginx/certs
    ports:
    - ${FRONT_PORT}:80
    networks:
      - docker_net
    links:
      - backend
      - file_server
    restart: always

networks:
  postgres_net:
    external: false
  mognodb_mongodb_net:
    external: true
  docker_net:
    external: false
