version: '3'

services:
  backend:
    build:
      context: ./src/backend
      dockerfile: Dockerfile
    environment:
      BACKEND_PORT: ${BACKEND_PORT}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_ADDRESS: ${MONGO_ADDRESS}
    networks:
      - postgres_net
      - mongo_mongodb_net
      - docker_net

  server:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - /etc/localtime:/etc/localtime/:ro
    ports:
    - ${FRONT_PORT}:80
    networks:
      - docker_net
    links:
      - backend
    restart: always

networks:
  postgres_net:
    external: true
  mongo_mongodb_net:
    external: true
  docker_net:
    external: false