version: '3'

services:
    mongodb:
        hostname: mongodb
        image: mongo:4.2.3
        container_name: mongodb
        ports:
            - ${MONGO_PORT}:27017
        volumes:
            - ./data/mongo:/data/db
        # uncomment the below line to setup mongo replica set!  But only after default setup! And then run rs.initiate() in mongo shell
#        entrypoint: ["/usr/bin/mongod", "--port", "27017", "--dbpath", "/data/db", "--replSet", "rs0", "--bind_ip", "mongodb,localhost"]
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
        networks:
            - mongodb_net

networks:
    mongodb_net:
        external: false